import axios from "axios"
import { useState, useEffect } from "react"
import Head from "next/head";
import Header from "@/components/header";
import { Screen } from ".";

export default function ChangeGamePage(props){

    function getExchange(){
        const URL = process.env.NEXT_PUBLIC_HOST;
        
        axios.get('')
    }

    return(
        <>
        <Head>
          <title>Gamestore</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="assets/logoIcon.svg" />
        </Head>
          <Header/>
          <Screen>
          </Screen>
          
      
        </>
    )
}