import Header from "@/components/header"
import Head from "next/head"
import SignUpForm from "@/components/signUpForm"
import styled from "styled-components"

export default function SignUp(){
    return(
        <>
        <Head>
          <title>Gamestore</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="assets/logoIcon.svg" />
        </Head>
          <Header/>
          <Screen>
            <SignUpForm/>
          </Screen>
          
      
        </>
    )
}

const Screen = styled.div`
  margin-top:150px;
  display: flex;
  flex-direction: column;
  align-items:center;
`