import Header from "@/components/header"
import Head from "next/head"

export default function SignUp(){
    return(
        <>
        <Head>
        <title>Gamestore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header/>
        </>
    )
}