import styled from "styled-components";
import { Screen } from "..";
import Header from '@/components/header'
import { TokenContext } from "../../../contexts/tokenContext";
import { useState, useContext } from "react";
import axios from "axios";
import Head from 'next/head'


export default function UserPage(props){

    const { userId } = props;
    const { token,image } = useContext(TokenContext);
    const [userInfo, setUserInfo] = useState({})

    async function GetUser(){
        const config = {
            headers:{
                Authorization: `Bearer ${token}`
            }
        }
        const URL = process.env.NEXT_PUBLIC_HOST;
        axios.get(`${URL}/users/${userId}`,config)
        .then((res) => setUserInfo(res.data))
        .catch((err) => console.log(err));
    }
    return(
        <>
            <Head>
                <title>Gamestore</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="../../assets/logoIcon.svg" />
            </Head>
            <Header/>
            <Screen>
                <UserPerfil>
                    <img src={image}/>
                </UserPerfil>
            </Screen>
        </>
    )
};

const UserPerfil = styled.div`
    display: flex;
    width: 400px;
    height: 400px;
    border-radius:8px;
    background: white;
    margin: 30px 0px;
    position: relative;

    img{
        position: absolute;
        top:10px;
        left: 10px;
        width: 50px;
        height: 50px;
        border-radius:50px;
    }
`

